### ISSUE TITLE
Добавить редактирование object в script_details.vue

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#107]
1)Добавить редактирование object в script_details.vue
2)Переместить script_details.vue в modals(так он, несомненно, модальное окно), и назвать так же, как остальные.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил редактирование object в script_details.vue, саму модалку переименовал и перенёс в папку к остальным модалкам. Залил в #110

**Comment by vvzvlad** [comment]
Работает
