### ISSUE TITLE
Еще одно поле при создании скрипта.

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#108]
Теперь логика сложнее.  В create_script_modal.vue:
1)Кроме поля name еще надо добавить поле object. 
2)Назвать его надо по-разному: для type=WEB_EVENT как "Endpoint", для BUS_EVENT "Topic", для DRIVER не надо показывать это поле вообще, для TIMER_EVENT как "Period(s)", для SHEDULE_EVENT как "Shedule". Все поля(кроме DRIVER) обязательное при создании скрипта. 
Сохраняется и загружается это поле всегда как object. 

Так же, вот эти переименования со временем коснуться всех страничек, где участвует object, так что стоит писать код с учетом этого(например, что-то вроде script_type2string, который я делал для имен типов).

**Comment by vvzvlad** [comment]
>А в остальных компонентах будем переименовывать object? Или там позже доберемся?

Да, по-хорошему, такое надо сделать везде, по тем же правилам. 
Кстати, посмотри в main.js:169 пример механизма vue, который сделан специально для такого, фильтра. Можно просто писать variable|filter_name, и будет показано то, что вернет filter_name при передаче в него variable. Как раз для превращения типа в текст подойдет. Перепиши на него script_type2string, object_label и nl2br?

**Comment by nismangulov** [comment]
@vvzvlad 

Переделал фильтры, залил в #129.

Единственное, пришлось в `files_table` делать небольшую магию - хедер таблицы задается не напрямую в `data`, а в хуке `mounted`, после первого рендера компонента. Так пришлось сделать, потому что до фильтров нельзя достучаться до инициализации компонента, а `data` задается как раз до этого. Внешне это никак не проявляется, просто не пугайся, когда увидишь это в коде.

**Comment by vvzvlad** [comment]
Работает.
