### ISSUE TITLE
Задержка при обновлении таблицы в bus

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#115]
После переключения в linear/tree таблица обновляется не сразу, а спустя период обновления. Сделать так, чтобы обновлялась сразу

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал запрос на обновление данных сразу после переключения вида таблицы. Лаг стал сильно меньше. Залил в #119.

Если нужно, можно совсем избавиться от лага - каждый раз запрашивать и хранить данные для обоих видов (таблица/дерево) и отображать только то, что нужно. Так лаг пропадет совсем, но запросы будут чуть больше грузить браузер и сеть.

**Comment by vvzvlad** [comment]
Да, так задержка пропала почти, можно больше ничего не делать
