### ISSUE TITLE
Перенести функционал linear в tree

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#123]
1)Добавить туда полный вид времени(использовать get_time(node.data.objectKey.update_time))
2)Добавить колонки type, tags
3)Добавить надпись "Bus records: " внизу таблицы.

**Comment by nismangulov** [comment]
@vvzvlad 

> 1)Добавить туда полный вид времени(использовать get_time(node.data.objectKey.update_time))

Искал функцию `get_time()`, но не нашёл. Нашёл только `$options.filters.toRelativeTime()`, но это вроде про относительное время. Писать свою функцию? Если да, тогда полный вид времени - это какой формат?

> 2)Добавить колонки type, tags

Добавил недостающие столбцы.

> 3)Добавить надпись "Bus records: " внизу таблицы.

Добавил надпись, считается она рекурсивным подсчетом объектов `__data__` в json-е, приходящем с бекенда. Цифры вроде совпадают с табличкой.

Залил все в #124

**Comment by nismangulov** [comment]
@vvzvlad 

Ага. Смержил мастера в пуллреквест, сделал форматирование времени через get_time(). Теперь все должно быть ок.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил text-overflow и title, чтобы полное значение столбца показывалось по ховеру.

**Comment by vvzvlad** [comment]
работает.
