### ISSUE TITLE
"развернуть все" и "свернуть все" в tree-view.

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#125]
Кнопки, которые будут разворачивать все топики и сворачивать.

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил две кнопки, залил в #131. 

Не нашёл, куда их лучше разместить, поэтому поставил их сюда
![image](https://user-images.githubusercontent.com/6184888/44566178-dfb1d100-a78d-11e8-90af-b52290b75a6c.png)

**Comment by vvzvlad** [comment]
Работает
