### ISSUE TITLE
Иконка "offline"/"online" рядом с адресом сервера

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#126]
Рядом с адресом сервера в верхнем баре расположить иконку (https://fontawesome.com/icons/link?style=solid), которая была бы зеленой, если соединение с сервером есть, и красной, если сервер не отвечает или отвечает чем-то отличным от правильного сообщения.
Проверять статус запросом get_git_version каждую секунду. Обновлять this.backend_version тоже каждую секунду. 

Title иконки: "Server connected" и "Server disconnected".

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал иконку и обновление backend_version каждую секунду. Если из бекенда пришла версия бекенда - значит все ок, иконка зелёная, а если бекенд не отдает версию или не отвечает - значит красная.

**Comment by vvzvlad** [comment]
Да, ок. А сделай так, чтобы если связи нет, то версия бекенда заменялась на "Disconnected"

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в #134

**Comment by vvzvlad** [comment]
Да, работает.
