### ISSUE TITLE
Разделители в боковом меню

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#127]
Сделать два разделителя:  между logs и drivers, и между web scripts и manage. Признак разделителя хранить в каждом пункте(если после пункта разделитель или нет, по умолчанию нет).
Разделитель стандартный: https://vuetifyjs.com/ru/components/dividers

**Comment by nismangulov** [comment]
@vvzvlad 

Добавил разделитель, флаг разделителя лежит в элементах массива `menu`. Залил в #133

**Comment by vvzvlad** [comment]
Работает.
