### ISSUE TITLE
Проблемы с логами в скриптах

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#128]
При количестве строк = 1 окно логов выглядит так: 
![image](https://user-images.githubusercontent.com/3315944/44544878-2ff04b00-a71c-11e8-8348-8a60ea5ed381.png)
При количестве строк = 0 происходит что-то страшное, страница падает, и продолжает падать при перезагрузке, пока не удалить из LS количество строк. Мне кажется, стоит ограничить минимальное количество строк 2-3.

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал минимальное количество строк, залил в #135

**Comment by vvzvlad** [comment]
работает.
