### ISSUE TITLE
Обрезается текст в модалках

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#136]
![image](https://user-images.githubusercontent.com/3315944/44580648-6329ed00-a7a3-11e8-83ce-32516d80b519.png)
Надо что-то с этим сделать. Либо расширять модалки, либо обрезать его с "..." и показывать title

**Comment by vvzvlad** [comment]
Да, пусть будет так.

**Comment by nismangulov** [comment]
@vvzvlad 

Поправил все кейсы со скриншотов, залил в #149

**Comment by vvzvlad** [comment]
Работает
