### ISSUE TITLE
Кнопка "запустить" в files_table

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#146]
У скриптов типа bus_event(только у них) появился вызов ?action=run_once, надо отразить кнопкой "запустить" в files_table. Кнопку сделать по подобию остальных кнопок(не стандартным компонентом, потому что он дико тормозит рендеринг списков). 
Использовать этот значок: https://fontawesome.com/icons/rocket?style=solid

**Comment by nismangulov** [comment]
@vvzvlad 

Сделал кнопку, залил в #151

**Comment by vvzvlad** [comment]
поправил, заработало
