### ISSUE TITLE
Адрес сервера в нижнем регистре

### ISSUE THREAD

**Issue by vvzvlad** [vvzvlad/glue_panel#148]
![image](https://user-images.githubusercontent.com/3315944/44921813-4580f880-ad4c-11e8-80e5-8459fb5d0e60.png)
Адрес сервера сделать в нижнем регистре. Это в файле glue_panel/src/main_page.vue

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в #152

**Comment by vvzvlad** [comment]
Работает
